name: Destroy AWS EC2
on: workflow_dispatch

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git pull
      uses: actions/checkout@v2
      
    - name: Terraform destroy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_SECRET }}
      run: |
        cd infra
        terraform init
        terraform destroy -auto-approve
