name: Test
on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: git pull
      uses: actions/checkout@v1
    - name: list files
      run: ls -l
      
    - name: Set env
      run: echo "$(cat ec2_dns_name)" >> $GITHUB_ENV
    - name: test
      run: echo ${{ env.GITHUB_ENV }}
    #- name: Deploy to my EC2 instance
     #   uses: easingthemes/ssh-deploy@v2.1.5
      #  env:
       #   SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        #  SOURCE: "./"
         # REMOTE_HOST: ${{ env.REMOTE_HOST_ENV }}
          #REMOTE_USER: "ubuntu"
          #TARGET: "/home/ec2-user/SampleExpressApp"      
