name: Test
on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git pull
      uses: actions/checkout@v2
    - name: Set env
      run: echo "HOSTNAME=$(cat ec2_dns_name)" >> $GITHUB_ENV
    - name: Test hostname
      run: echo ${{ env.HOSTNAME }}
      
    - name: Deploy in EC2
      uses: actions/checkout@v2 
    env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
            HOSTNAME : ${{ secrets.HOSTNAME }}
            USER_NAME : ${{ secrets.USER_NAME }}
    
