name: Test
on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git pull
      uses: actions/checkout@v2
    - name: Set env
      run: echo "HOSTNAME=$(cat ec2_dns_name | tr -d \")" >> $GITHUB_ENV
#    - name: Test hostname
#      run: echo ${{ env.HOSTNAME }}
      
    
#    - uses: actions/checkout@v2
    - name: Deploy in EC2  
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOSTNAME : ${{ env.HOSTNAME }}
        USER_NAME : ${{ secrets.USER_NAME }}  
      
      run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
          
          sudo docker exec -it apache2 /bin/bash
          #cd /git &&
          #sudo git checkout main &&
          git pull origin main
          cp -r CV/* /var/www/html/
          "
