name: Push code change to EC2
on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git pull
      uses: actions/checkout@v2
    - name: Set env
      run: echo "HOSTNAME=$(cat infra/ec2_dns_name | tr -d \")" >> $GITHUB_ENV
#    - name: Test hostname
#      run: echo ${{ env.HOSTNAME }}
      
    
#    - uses: actions/checkout@v2
    - name: Push to EC2  
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOSTNAME : ${{ env.HOSTNAME }}
        USER_NAME : ${{ secrets.USER_NAME }}  
      
      run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
  
          ssh -i private_key ${USER_NAME}@${HOSTNAME} "
          
          sudo docker exec -i apache2 git pull origin main
          sudo docker exec -i apache2 sh -c 'cp -r /var/www/html/CV/* /var/www/html/'
          "
