name: Push code change to EC2
on: 
  push:
    paths:
      - 'CV/**'

jobs:
  push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git pull
      uses: actions/checkout@v2

    - name: Push to EC2  
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOSTNAME : didenkoantoncv.pp.ua
        USER_NAME : ${{ secrets.USER_NAME }}  
      
      run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
  
          ssh -i private_key ${USER_NAME}@${HOSTNAME} "
          
          sudo docker exec -i apache2 git pull origin main
          sudo docker exec -i apache2 sh -c 'cp /var/www/html/CV/* /var/www/html/'
          "
