name: Test_name
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git pull
      uses: actions/checkout@v2
      
    - name: Check HTML
      uses: chabad360/htmlproofer@master
      with:
        directory: "/home/runner/work/Symphony_test/Symphony_test/CV"
        # The directory to scan
        arguments: --allow-missing-href
        # The arguments to pass to HTMLProofer
