name: Test_name
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git pull
      uses: actions/checkout@v2
      
    - name: Set ENV
      run: |
        cd infra
        terraform init
        echo "IP_ADDR=$(terraform output ec2instance_ip | tr -d \")" >> $GITHUB_ENV
      
    - name: Change NS record
      run: |
        curl -u iSTKr:${{ secrets.DNS_PROVIDER_PASS }} "http://api.geoscaling.com/dns2/dynamic/?host=didenkoantoncv.pp.ua&content=$IP_ADDR"
