name: Test_name
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git pull
      uses: actions/checkout@v2
      
    - name: Check HTTP 200 ok
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOSTNAME : didenkoantoncv.pp.ua
        USER_NAME : ${{ secrets.USER_NAME }}
      run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
  
          ssh -i private_key ${USER_NAME}@${HOSTNAME} "
          curl --write-out "%{http_code}\n" --silent --output /dev/null "didenkoantoncv.pp.ua"
          "
