name: Test_name
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Change NS record
      run: curl -u iSTKr:${{ secrets.DNS_PROVIDER_PASS }} "http://api.geoscaling.com/dns2/dynamic/?host=didenkoantoncv.pp.ua&content=2.2.2.2"
